configure requires that you specify either qt4 or qt5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,7 +20,8 @@ echo "  --generator=<name>           use given code generator (-G in cmake, whic
 echo "  --verbose-build (or --verbose or -v) turn on verbose make output: for make probs"
 echo "  --not-native                 don't define -march=native for compilation, which is otherwise the default -- only needed for making packages that will run more broadly"
 echo "  --emer-mac-arch-bits=NN      set up for 32-bit or 64-bit compilation"
-echo "  --qt5                        configure for Qt5 -- must set QTDIR enviro var to qt install dir (e.g., home/Qt5.0.0/5.0.0/clang_64)"
+echo "  --qt5                        configure for Qt5 -- must set QTDIR enviro var to qt install dir (e.g., /usr/local/Qt5.2.0/5.2.0/clang_64)"
+echo "  --qt4                        configure for Qt4 -- either qt5 or 4 must be explicitly set, just to be sure you got the right one"
 echo "  --c++11                      enable c++11 support, using e.g., -std=c++11 flag"
 echo "  --sse8                       define USE_SSE8 to take advantage of 8-way parallel SIMD (SSE) ops -- only useful for clang compiler, where it is auto-enabled"
 echo " "
@@ -31,12 +32,16 @@ cmake_cmd="cmake ../"
 build_dir="build"
 extra_suffix=""
 not_native=""
+qt_version=""
 
 while [ $# -gt 0 ]
 do
   preq=${1%=*}			# get part before =
   case $preq
   in
+    --help | -help | help)
+      exit 0
+    ;;
     --suffix | -suffix | suffix)
       extra_suffix=${1##*=}		# get part after =
       cmake_cmd="$cmake_cmd -DEXTRA_SUFFIX=$extra_suffix"
@@ -107,6 +112,13 @@ do
 
     --qt5 | -qt5 | qt5)
       cmake_cmd="$cmake_cmd -DQT_USE_5=ON -DQTDIR=$QTDIR"
+      qt_version="qt5"
+      shift 1
+    ;;
+
+    --qt4 | -qt4 | qt4)
+      cmake_cmd="$cmake_cmd -DQT_USE_4=ON -DQTDIR=$QTDIR"
+      qt_version="qt4"
       shift 1
     ;;
 
@@ -126,6 +138,11 @@ do
     ;;
   esac
 done
+
+if [[ "$qt_version" == "" ]]; then
+    echo "ERROR: you must specify either qt5 or qt4 -- pretty soon it will default to qt5, but right now there is enough ambiguity that you must specify which one explicitly."
+    exit 1
+fi
 
 if [[ $verbose_build == "true" ]]; then
     cmake_cmd="$cmake_cmd -DCMAKE_VERBOSE_MAKEFILE=ON"
