* fixed plugins to work with QT5 -- auto-detect qt based on current running version * updated plugin template configure script

diff --git a/plugins/template/configure b/plugins/template/configure
--- a/plugins/template/configure
+++ b/plugins/template/configure
@@ -16,6 +16,12 @@ echo "  --clean                      clean existing cmake cache etc first: start
 echo "  --build-dir=<name>           provide a custom build directory name (else auto)"
 echo "  --generator=\"<name>\"         use given code generator *IN QUOTES* (-G in cmake, which also works)"
 echo "  --verbose-build (or --verbose or -v) turn on verbose make output: for make probs"
+echo "  --not-native                 don't define -march=native for compilation, which is otherwise the default -- only needed for making packages that will run more broadly"
+echo "  --emer-mac-arch-bits=NN      set up for 32-bit or 64-bit compilation"
+echo "  --qt5                        configure for Qt5 -- must set QTDIR enviro var to qt install dir (e.g., /usr/local/Qt5.2.0/5.2.0/clang_64)"
+echo "  --qt4                        configure for Qt4 -- either qt5 or 4 must be explicitly set, just to be sure you got the right one"
+echo "  --c++11                      enable c++11 support, using e.g., -std=c++11 flag"
+echo "  --sse8                       define USE_SSE8 to take advantage of 8-way parallel SIMD (SSE) ops -- only useful for clang compiler, where it is auto-enabled"
 echo "  --yes (or --y or -y)         do not pause for confirmation before running cmake"
 echo " "
 echo "  (note: -- before args is optional, and - works too!)"
@@ -24,12 +30,18 @@ echo " "
 cmake_cmd="cmake ../"
 build_dir="build"
 prefix="User"
+extra_suffix=""
+not_native=""
+qt_version=""
 
 while [ $# -gt 0 ]
 do
   preq=${1%=*}			# get part before =
   case $preq
   in
+    --help | -help | help)
+      exit 0
+    ;;
     --suffix | -suffix | suffix)
       extra_suffix=${1##*=}		# get part after =
       cmake_cmd="$cmake_cmd -DEXTRA_SUFFIX=$extra_suffix"
@@ -78,8 +90,36 @@ echo "generator command is not working -- omit to use the default, 'Unix Makefil
 exit 1
     ;;
 
-    --help | -help | help)
-      help=true
+    --not-native | -not-native | not-native)
+      not_native="not-native"
+      cmake_cmd="$cmake_cmd -DNOT_NATIVE=not-native"
+      shift 1
+    ;;
+
+    --emer-mac-arch-bits)
+      cmake_cmd="$cmake_cmd -DEMER_MAC_ARCH_BITS=${1##*=}"
+      shift 1
+    ;;
+
+    --qt5 | -qt5 | qt5)
+      cmake_cmd="$cmake_cmd -DQT_USE_5=ON -DQTDIR=$QTDIR"
+      qt_version="qt5"
+      shift 1
+    ;;
+
+    --qt4 | -qt4 | qt4)
+      cmake_cmd="$cmake_cmd -DQT_USE_4=ON -DQTDIR=$QTDIR"
+      qt_version="qt4"
+      shift 1
+    ;;
+
+    --sse8 | -sse8 | sse8)
+      cmake_cmd="$cmake_cmd -DCMAKE_CXX_FLAGS=-DUSE_SSE8"
+      shift 1
+    ;;
+
+    --c++11 | -c++11 | c++11)
+      cmake_cmd="$cmake_cmd -DCMAKE_CXX_FLAGS=-std=c++11"
       shift 1
     ;;
 
@@ -95,8 +135,9 @@ exit 1
   esac
 done
 
-if [[ $help == "true" ]]; then
-  exit
+if [[ "$qt_version" == "" ]]; then
+    echo "ERROR: you must specify either qt5 or qt4 -- pretty soon it will default to qt5, but right now there is enough ambiguity that you must specify which one explicitly."
+    exit 1
 fi
 
 if [[ $verbose_build == "true" ]]; then
@@ -118,11 +159,13 @@ echo "  prefix:       $prefix"
 echo "  mpi:          $mpi"
 echo "  clean:        $clean"
 echo "  build-dir:    $build_dir"
+echo "  qt-version:   $qt_version"
 echo "  generator:    $generator"
 echo "  verbose:      $verbose_build"
 echo " "
 echo "  cmake command: $cmake_cmd"
 echo " "
+
 if [[ $yes != "true" ]]; then
   read -p "Press any key to continue (Ctrl-C to cancel)..."
 fi
